
logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      target: stderr

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9000

swagger:
  resourcePackage: dk.osaa.psaw.web.resources 


machine:
   serialPort: /dev/ttyACM0
   simulating: false
   recording: false
   #recordDir:
   jobsDir: jobs
   jobsInMemory: 10
   assistAirDelay: 500
   maximumLaserPower: 80
   junctionDeviation: 0.1
   rapidMoveSpeed: 5000
   tickHZ: 50000
   shortestMove: 0.2
   laserCalibration: 2e 2e 2e 2e 2e 2f 2f 2f 2f 2f 2f 2f 2f 30 30 30 31 32 33 34 35 36 36 37 38 39 3a 3b 3c 3d 3d 3e 3f 40 40 41 41 42 42 43 43 44 44 45 45 46 46 47 47 48 48 49 49 4a 4a 4b 4b 4c 4c 4d 4d 4e 4e 4f 4f 50 50 51 51 52 52 53 53 53 54 54 55 55 56 56 57 57 58 58 59 59 5a 5a 5b 5b 5c 5c 5d 5d 5e 5e 5f 5f 60 60 61 62 62 63 64 64 65 65 66 67 67 68 69 69 6a 6a 6b 6c 6c 6d 6e 6e 6f 6f 70 71 71 72 73 73 74 74 75 76 76 77 78 78 79 79 7a 7b 7b 7c 7d 7d 7e 7f 7f 80 83 85 87 89 8b 8e 90 92 94 96 99 9b 9d 9f a1 a2 a4 a5 a7 a8 aa ab ac ae af b1 b2 b4 b5 b7 b8 ba bb bd be c0 c3 c6 c9 cc cf d1 d4 d7 da dd df e0 e1 e1 e2 e2 e3 e4 e4 e5 e6 e6 e7 e8 e8 e9 e9 ea eb eb ec ed ed ee ee ef f0 f0 f0 f1 f1 f2 f2 f3 f3 f4 f4 f5 f5 f6 f6 f7 f7 f7 f8 f8 f9 f9 fa fa fb fb fc fc fd fd fe fe ff ff
   axes:
      x:
         acceleration: 6000
         maxSpeed: 1500
         minSpeed: 20
         maxJerk: 10
         mmPerStep: 0.0375
         coilCurrent: 1800
         microSteppingMode: 3
      y:
         acceleration: 500
         maxSpeed: 1500
         minSpeed: 20
         maxJerk: 10
         mmPerStep: 0.03754
         coilCurrent: 1800
         microSteppingMode: 3
      z:
         acceleration: 0.1
         maxSpeed: 10
         minSpeed: 0.2
         maxJerk: 100
         mmPerStep: 0.003125
         coilCurrent: 1500
         microSteppingMode: 3 
      a:
         acceleration: 5000
         maxSpeed: 10
         minSpeed: 1
         maxJerk: 1
         mmPerStep: 0.02
         coilCurrent: 350
         microSteppingMode: 3
   